"""docgen — vistas generadas + ratchet anti-copia.

El codigo es la fuente mecanica (modulos, tools MCP, conteos). Este modulo
(1) escribe `docs/generated/catalog.md` y refresca bloques `<!-- mmorch:auto:* -->`
en el README; (2) en `--check`, falla si el catalogo esta stale o si un contrato
(GOAL/AGENTS/CLAUDE/CONTEXT/capabilities/SOURCES) copio keys de REGISTRY, tools
MCP, o conteos que viven en el catalogo.

Uso:
    python -m mmorch.docgen            # regenera catalogo + README
    python -m mmorch.docgen --check    # exit 1 si stale o copia prohibida
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "mmorch"
README = ROOT / "README.md"
GENERATED = ROOT / "docs" / "generated"
CATALOG = GENERATED / "catalog.md"

_SKIP = {"__init__.py", "docgen.py"}

# Contratos: punteros y reglas. Nunca catalogos. El bloque Beads se ignora
# (plantilla externa; menciona tools de memoria).
_CONTRACTS = (
    "GOAL.md",
    "AGENTS.md",
    "CLAUDE.md",
    "CONTEXT.md",
    "docs/SOURCES.md",
    "docs/capabilities.md",
)

_TOOL_RE = re.compile(r"\bmmorch_[a-z][a-z0-9_]*\b")
_COUNT_TESTS_RE = re.compile(r"\b\d+\s+tests\b", re.I)
_COUNT_TOOLS_RE = re.compile(r"\b\d+\s+tools\b", re.I)
_BEADS_RE = re.compile(
    r"<!-- BEGIN BEADS INTEGRATION.*?<!-- END BEADS INTEGRATION.*?-->", re.S
)


def _first_doc_line(py: Path) -> str:
    txt = py.read_text(encoding="utf-8")
    m = re.search(r'^\s*(?:"""|\'\'\')(.+?)(?:\n|"""|\'\'\')', txt, re.S)
    if not m:
        return ""
    return m.group(1).strip().splitlines()[0].strip()


def module_table() -> str:
    rows = ["| Módulo | Qué hace |", "|---|---|"]
    for py in sorted(PKG.glob("*.py")):
        if py.name in _SKIP:
            continue
        desc = _first_doc_line(py) or "(sin docstring)"
        rows.append(f"| `mmorch/{py.name}` | {desc} |")
    return "\n".join(rows)


def mcp_tools() -> list[str]:
    src = PKG / "mcp_server.py"
    if not src.exists():
        return []
    txt = src.read_text(encoding="utf-8")
    return sorted(set(re.findall(r"def (mmorch_\w+)\s*\(", txt)))


def stats() -> dict:
    n_mod = len([p for p in PKG.glob("*.py") if p.name not in _SKIP])
    tdir = ROOT / "tests"
    n_tests = 0
    if tdir.exists():
        for tf in tdir.glob("test_*.py"):
            n_tests += len(re.findall(r"^\s*def test_\w+", tf.read_text(encoding="utf-8"), re.M))
    return {"modules": n_mod, "tools": len(mcp_tools()), "tests": n_tests}


def catalog_markdown() -> str:
    s = stats()
    tools = mcp_tools()
    tool_line = ", ".join(f"`{t}`" for t in tools)
    return (
        "<!-- Generated by python -m mmorch.docgen. Do not edit. -->\n\n"
        "# Catálogo (generado)\n\n"
        "Fuente: introspección de `mmorch/*.py` (1ª línea del docstring) y "
        "`mmorch/mcp_server.py`. Contratos y ‘cuándo elegir’: ver `docs/SOURCES.md`.\n\n"
        f"**{s['modules']} módulos · {s['tools']} MCP tools · {s['tests']} tests.**\n\n"
        "## Módulos\n\n"
        f"{module_table()}\n\n"
        "## MCP tools\n\n"
        f"{tool_line}.\n"
    )


def render_block(name: str) -> str:
    if name == "stats":
        s = stats()
        return (f"_Auto-generado por `mmorch.docgen`._ "
                f"**{s['modules']} módulos · {s['tools']} MCP tools · {s['tests']} tests.** "
                "Catálogo: [`docs/generated/catalog.md`](docs/generated/catalog.md).")
    if name == "modules":
        return ("Tabla de módulos: [`docs/generated/catalog.md`](docs/generated/catalog.md). "
                "No editar a mano.")
    if name == "tools":
        return ("Lista de tools: [`docs/generated/catalog.md`](docs/generated/catalog.md#mcp-tools). "
                "**Restart Claude Code** to load new tools.")
    raise ValueError(f"bloque desconocido: {name}")


def _replace_auto_blocks(txt: str) -> tuple[str, list[str]]:
    updated = []
    for name in ("modules", "tools", "stats"):
        start = f"<!-- mmorch:auto:{name} -->"
        end = f"<!-- /mmorch:auto:{name} -->"
        # ponytail: find/slice en vez de re.sub — un callable de reemplazo
        # hace pelear a ruff (B023) con mypy (misc), y el render trae backslashes.
        i0 = txt.find(start)
        j0 = txt.find(end, i0 + 1)
        if i0 < 0 or j0 < 0:
            continue
        block = f"{start}\n{render_block(name)}\n{end}"
        txt = txt[:i0] + block + txt[j0 + len(end):]
        updated.append(name)
    return txt, updated


def update_readme(path: Path = README) -> list[str]:
    """Reemplaza cada bloque entre marcadores. Idempotente."""
    txt, updated = _replace_auto_blocks(path.read_text(encoding="utf-8"))
    path.write_text(txt, encoding="utf-8")
    return updated


def update_generated(path: Path = CATALOG) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(catalog_markdown(), encoding="utf-8")


def strip_beads(text: str) -> str:
    return _BEADS_RE.sub("", text)


def _registry_keys() -> list[str]:
    from .config import REGISTRY
    return sorted(REGISTRY, key=len, reverse=True)


def contract_hits(text: str, keys: list[str] | None = None) -> list[str]:
    """Copias prohibidas en un contrato (Beads ya strippeado)."""
    body = strip_beads(text)
    keys = keys if keys is not None else _registry_keys()
    hits: list[str] = []
    for k in keys:
        if k in body:
            hits.append(f"registry key {k!r}")
    for m in _TOOL_RE.finditer(body):
        hits.append(f"mcp tool {m.group(0)!r}")
    if _COUNT_TESTS_RE.search(body):
        hits.append("stale test-count (vive en docs/generated/catalog.md)")
    if _COUNT_TOOLS_RE.search(body):
        hits.append("stale tool-count (vive en docs/generated/catalog.md)")
    return hits


def ssot_violations(root: Path = ROOT) -> list[str]:
    keys = _registry_keys()
    out: list[str] = []
    for rel in _CONTRACTS:
        p = root / rel
        if not p.exists():
            continue
        for h in contract_hits(p.read_text(encoding="utf-8"), keys):
            out.append(f"{rel}: {h}")
    return out


def check(root: Path = ROOT) -> list[str]:
    """Stale generated/README + copias en contratos. Vacio = OK."""
    problems: list[str] = []
    cat = root / "docs" / "generated" / "catalog.md"
    expected = catalog_markdown()
    if not cat.exists() or cat.read_text(encoding="utf-8") != expected:
        problems.append("docs/generated/catalog.md stale — corre python -m mmorch.docgen")
    readme = root / "README.md"
    if readme.exists():
        got = readme.read_text(encoding="utf-8")
        want, _ = _replace_auto_blocks(got)
        if got != want:
            problems.append("README.md auto-blocks stale — corre python -m mmorch.docgen")
    problems.extend(ssot_violations(root))
    return problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="mmorch.docgen")
    ap.add_argument("--check", action="store_true",
                    help="falla si catalogo/README stale o contratos copian catalogos")
    args = ap.parse_args(argv)
    if args.check:
        probs = check()
        if probs:
            print("docgen --check FAIL:", file=sys.stderr)
            for p in probs:
                print(f"  {p}", file=sys.stderr)
            return 1
        print(f"docgen --check OK | {stats()}")
        return 0
    update_generated()
    up = update_readme()
    print(f"catalogo+README actualizados: bloques {up} | {stats()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
